server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6t7c1ruibrs73cnuocg-a.oregon-postgres.render.com:5432/food_web
spring.datasource.username=jai_postgres_user
spring.datasource.password=W2LvN35ejmUdELVrxHd7Tw2OxdHq589t
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=dj2zcuqzt
cloudinary.api_key=861942856239387
cloudinary.api_secret=8SC-tRKlGDYvDT8Uc-QkCbimAUs