spring.datasource.url=postgresql://food_data_jq4g_user:2Z3dua3zF0LbTYYH13DKPUwwAkoE1213@dpg-d6tr3l24d50c73cg2nbg-a.oregon-postgres.render.com/food_data_jq4g
spring.datasource.username=food_data_jq4g_user
spring.datasource.password=2Z3dua3zF0LbTYYH13DKPUwwAkoE1213
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true